"""add public_id column to DiagnosisRecord

Revision ID: 01d2ddb9bfa3
Revises: 5b579632ab5c
Create Date: 2025-12-21 16:43:31.034263

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01d2ddb9bfa3"
down_revision: Union[str, Sequence[str], None] = "5b579632ab5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("diagnosis_record", sa.Column("public_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_diagnosis_record_public_id"),
        "diagnosis_record",
        ["public_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnosis_record_public_id"), table_name="diagnosis_record")
    op.drop_column("diagnosis_record", "public_id")
    # ### end Alembic commands ###
