"""Add url's fields for diagnosis records

Revision ID: 218f441939c3
Revises: 01d2ddb9bfa3
Create Date: 2025-12-21 20:06:31.552757

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218f441939c3"
down_revision: Union[str, Sequence[str], None] = "01d2ddb9bfa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diagnosis_record", sa.Column("result_image_url", sa.String(), nullable=False)
    )
    op.add_column(
        "diagnosis_record",
        sa.Column("explanation_image_url", sa.String(), nullable=False),
    )
    op.add_column(
        "diagnosis_record", sa.Column("gradcam_image_url", sa.String(), nullable=False)
    )
    op.drop_column("diagnosis_record", "diagnosis_image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diagnosis_record",
        sa.Column(
            "diagnosis_image_url", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("diagnosis_record", "gradcam_image_url")
    op.drop_column("diagnosis_record", "explanation_image_url")
    op.drop_column("diagnosis_record", "result_image_url")
    # ### end Alembic commands ###
