"""Remove Not Null constraints from email

Revision ID: 452d68d324a1
Revises: dce97f92b085
Create Date: 2025-09-19 11:54:15.313435

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "452d68d324a1"
down_revision: Union[str, Sequence[str], None] = "dce97f92b085"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=320), nullable=False
    )
    # ### end Alembic commands ###
