"""Add diagnosis_record user relationship, JSON diagnosis data, and timezone-aware timestamp

Revision ID: 5b579632ab5c
Revises: ab7edb1a6ef5
Create Date: 2025-12-21 16:07:03.396834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b579632ab5c"
down_revision: Union[str, Sequence[str], None] = "ab7edb1a6ef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnosis_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("uploaded_image_url", sa.String(), nullable=False),
        sa.Column("diagnosis_image_url", sa.String(), nullable=False),
        sa.Column("report_url", sa.String(), nullable=False),
        sa.Column("diagnosis_data", sa.JSON(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnosis_record_user_id"),
        "diagnosis_record",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnosis_record_user_id"), table_name="diagnosis_record")
    op.drop_table("diagnosis_record")
    # ### end Alembic commands ###
