"""First migrations

Revision ID: b6ded5980e45
Revises:
Create Date: 2026-03-16 01:55:42.295686

"""

from typing import Sequence, Union

import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6ded5980e45"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_configuration",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_configuration_key"),
        "system_configuration",
        ["key"],
        unique=True,
    )
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column(
            "user_type",
            sa.Enum("USER", "DOCTOR", name="user_type_enum"),
            nullable=False,
        ),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("last_credit_reset_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", GUID(), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_phone_number"), "user", ["phone_number"], unique=True)
    op.create_table(
        "appointment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", GUID(), nullable=False),
        sa.Column("doctor_id", GUID(), nullable=False),
        sa.Column("appointment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_slot", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "COMPLETED",
                "CANCELLED",
                name="appointment_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("patient_notes", sa.String(), nullable=True),
        sa.Column("doctor_notes", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointment_doctor_id"), "appointment", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointment_patient_id"), "appointment", ["patient_id"], unique=False
    )
    op.create_table(
        "diagnosis_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("public_id", sa.String(), nullable=False),
        sa.Column("uploaded_image_url", sa.String(), nullable=False),
        sa.Column("result_image_url", sa.String(), nullable=False),
        sa.Column("explanation_image_url", sa.String(), nullable=False),
        sa.Column("gradcam_image_url", sa.String(), nullable=False),
        sa.Column("report_url", sa.String(), nullable=False),
        sa.Column("diagnosis_data", sa.JSON(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("review_status", sa.String(), nullable=True),
        sa.Column("reviewer_id", GUID(), nullable=True),
        sa.Column("review_notes", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_diagnosis_record_user_id"),
        "diagnosis_record",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "doctor_verification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", GUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("specialty", sa.String(), nullable=False),
        sa.Column("license_number", sa.String(), nullable=False),
        sa.Column("hospital_or_clinic", sa.String(), nullable=True),
        sa.Column("document_url", sa.String(), nullable=True),
        sa.Column("additional_notes", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="verification_status_enum"),
            nullable=False,
        ),
        sa.Column("admin_notes", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_doctor_verification_doctor_id"),
        "doctor_verification",
        ["doctor_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_doctor_verification_status"),
        "doctor_verification",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_doctor_verification_status"), table_name="doctor_verification"
    )
    op.drop_index(
        op.f("ix_doctor_verification_doctor_id"), table_name="doctor_verification"
    )
    op.drop_table("doctor_verification")
    op.drop_index(op.f("ix_diagnosis_record_user_id"), table_name="diagnosis_record")
    op.drop_table("diagnosis_record")
    op.drop_index(op.f("ix_appointment_patient_id"), table_name="appointment")
    op.drop_index(op.f("ix_appointment_doctor_id"), table_name="appointment")
    op.drop_table("appointment")
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        op.f("ix_system_configuration_key"), table_name="system_configuration"
    )
    op.drop_table("system_configuration")
    # ### end Alembic commands ###
