"""Remove UUID for public id

Revision ID: fb3b72d1d895
Revises: 218f441939c3
Create Date: 2025-12-21 20:20:57.712364

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb3b72d1d895"
down_revision: Union[str, Sequence[str], None] = "218f441939c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "diagnosis_record",
        "public_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_diagnosis_record_public_id"), table_name="diagnosis_record")
    op.create_unique_constraint(None, "diagnosis_record", ["public_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "diagnosis_record", type_="unique")
    op.create_index(
        op.f("ix_diagnosis_record_public_id"),
        "diagnosis_record",
        ["public_id"],
        unique=True,
    )
    op.alter_column(
        "diagnosis_record",
        "public_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
